---
title: "Comparison of length in significant and negative pairs"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
sig_pair$source <- "sig"
neg_pair$source <- "neg"
combined_df_delmonte <- rbind(sig_pair[,c(10,11)], neg_pair[,c(7,9)])
```

```{r}
ggplot(combined_df_delmonte, aes(x = length, fill = source, y = ..density..)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1, boundary = 0.5) +
  scale_x_continuous(limits = c(8, 20), breaks = seq(8, 20, by = 1)) +
  labs(title = "Delmonte_length_dist", x = "Length", y = "Density") +
  theme_minimal()
```

```{r}
emerson_test$source <- "sig"
emerson_test[emerson_test$class == 0,]$source <- "neg"
```

```{r}
ggplot(emerson_test, aes(x = length, fill = source, y = ..density..)) +
  geom_histogram(position = "identity", alpha = 0.5, binwidth = 1, boundary = 0.5) +
  scale_x_continuous(limits = c(8, 20), breaks = seq(8, 20, by = 1)) +
  labs(title = "Emerson_length_dist", x = "Length", y = "Density") +
  theme_minimal()
```

