---
title: "Untitled"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(pROC)
```

```{r}
Ortega <- read_csv("/Users/fuminli/Desktop/paper_revision/Ortega_I_pairs.csv")
Ortega_DePTH1 <- read_csv("/Users/fuminli/Desktop/paper_revision/Ortega_output_DePTH1/predicted_scores.csv")
Ortega_DePTH2 <- read_csv("/Users/fuminli/Desktop/paper_revision/Ortega_output_DePTH2/predicted_scores.csv")
```


```{r}
roc1_df <- data.frame(
  TPR = rev(roc1$sensitivities),
  FPR = rev(1 - roc1$specificities),
  model = "DePTH1"
)

roc2_df <- data.frame(
  TPR = rev(roc2$sensitivities),
  FPR = rev(1 - roc2$specificities),
  model = "DePTH2"
)

# 合并
roc_df <- rbind(roc1_df, roc2_df)

```

```{r}
figure1 <- ggplot(roc_df, aes(x = FPR, y = TPR, color = model)) +
  geom_line(size = 1.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", size = 1.2) +
  scale_color_manual(
    values = c("DePTH1" = "blue", "DePTH2" = "purple"),
    labels = c(
      paste0("DePTH1.0: ", round(auc(roc1), 2)),
      paste0("DePTH2.0: ", round(auc(roc2), 2))
    )
  ) +
  labs(title = "(A) DePTH on Ortega(HLA-I)",
       x = "FPR", y = "TPR") +
  theme_minimal() +
  theme(
    legend.position = c(1.18, 0.05),
    legend.justification = c(1.25, 0),
    legend.title = element_blank(),
    legend.background = element_rect(linetype = "solid", colour = "black"),
    legend.text = element_text(size = 20, face = "bold"),
    plot.title = element_text(size = 20, face = "bold"),
    axis.title = element_text(size = 20, face = "bold"),
    axis.text = element_text(size = 20, face = "bold"),
    legend.key.size = unit(1.5, 'lines')
  ) +
  coord_fixed()

```



```{r}
library(patchwork)

combined_plot <- (figure1 + figure2 + figure3) + 
  plot_layout(nrow = 1, widths = c(1, 1, 1))  
print(combined_plot)

```
```{r}
ggsave("combined_plot.pdf", plot = combined_plot, width = 18, height = 6)  

```



