---
title: "model_comparison_depth_tgp"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
emerson_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/emerson_pairs_I.csv")
tcga_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/tcga_pairs.csv")
```

# normalization

```{r}
emerson_pairs_I$normalized_tgp <- (log10(emerson_pairs_I$tgp) + 5) / (-5)
tcga_pairs_I$normalized_tgp <- (log10(tcga_pairs_I$tgp) + 5) / (-5)

emerson_pairs_I[emerson_pairs_I$normalized_tgp > 1,]$normalized_tgp <- 1
#tcga_pairs_I[tcga_pairs_I$normalized_tgp > 1,]$normalized_tgp <- 1
```

```{r}
model <- glm(as.factor(class) ~ score + normalized_tgp + score*normalized_tgp, data = emerson_pairs_I, family = binomial)
predicted <- predict(model, type = "response")
emerson_pairs_I$combined_score <- predicted
```

```{r}
roc_emerson_tgp <- roc(emerson_pairs_I$class, emerson_pairs_I$normalized_tgp)

roc_emerson_tgp_df <- data.frame(
  FPR = 1-roc_emerson_tgp$specificities,
  TPR = roc_emerson_tgp$sensitivities
)

roc_emerson_depth <- roc(emerson_pairs_I$class, emerson_pairs_I$score)

roc_emerson_depth_df <- data.frame(
  FPR = 1-roc_emerson_depth$specificities,
  TPR = roc_emerson_depth$sensitivities
)

roc_emerson_combined_score <- roc(emerson_pairs_I$class, emerson_pairs_I$combined_score)

roc_emerson_combined_score_df <- data.frame(
  FPR = 1-roc_emerson_combined_score$specificities,
  TPR = roc_emerson_combined_score$sensitivities
)
```

```{r}
ggplot() +
  geom_line(data = roc_emerson_combined_score_df, aes(x = FPR, y = TPR, color = "TGP+DePTH"), size = 1) +
  geom_line(data = roc_emerson_depth_df, aes(x = FPR, y = TPR, color = "DePTH"), size = 1) +
  geom_line(data = roc_emerson_tgp_df, aes(x = FPR, y = TPR, color = "TGP"), size = 1) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("TGP" = "blue",
                                 "DePTH" = "purple",
                                "TGP+DePTH" = "green"),
                     labels = c("TGP" = paste("TGP: ", round(roc_emerson_tgp$auc,3)),"DePTH" = paste("DePTH ", round(roc_emerson_depth$auc,3)), "TGP+DePTH" = paste("TGP+DePTH: ", round(roc_emerson_combined_score$auc,3)))) +
  labs(
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(legend.position = c(1.19, -0.01), 
        legend.justification = c(1.32, -0.25), 
        legend.title = element_blank(),
        legend.background = element_rect(linetype = "solid", colour = "black"),
        legend.text = element_text(size = 15, face = "bold"),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 15)) + 
        coord_fixed() +
  theme(panel.background = element_rect(fill = "white", color = NA))
  
```
```{r}
model <- glm(as.factor(class) ~ score + normalized_tgp + score*normalized_tgp, data = tcga_pairs_I, family = binomial)
predicted <- predict(model, type = "response")
tcga_pairs_I$combined_score <- predicted
```

```{r}
roc_tcga_tgp <- roc(tcga_pairs_I$class, tcga_pairs_I$normalized_tgp)

roc_tcga_tgp_df <- data.frame(
  FPR = 1-roc_tcga_tgp$specificities,
  TPR = roc_tcga_tgp$sensitivities
)

roc_tcga_depth <- roc(tcga_pairs_I$class, tcga_pairs_I$score)

roc_tcga_depth_df <- data.frame(
  FPR = 1-roc_tcga_depth$specificities,
  TPR = roc_tcga_depth$sensitivities
)

roc_tcga_combined_score <- roc(tcga_pairs_I$class, tcga_pairs_I$combined_score)

roc_tcga_combined_score_df <- data.frame(
  FPR = 1-roc_tcga_combined_score$specificities,
  TPR = roc_tcga_combined_score$sensitivities
)
```

```{r}
ggplot() +
  geom_line(data = roc_tcga_combined_score_df[270:1,], aes(x = FPR, y = TPR, color = "TGP+DePTH"), size = 1) +
  geom_line(data = roc_tcga_depth_df[270:1,], aes(x = FPR, y = TPR, color = "DePTH"), size = 1) +
  geom_line(data = roc_tcga_tgp_df[270:1,], aes(x = FPR, y = TPR, color = "TGP"), size = 1) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("TGP" = "blue",
                                 "DePTH" = "purple",
                                "TGP+DePTH" = "green"),
                     labels = c("TGP" = paste("TGP: ", round(roc_tcga_tgp$auc,2)),"DePTH" = paste("DePTH ", round(roc_tcga_depth$auc,2)), "TGP+DePTH" = paste("TGP+DePTH: ", round(roc_tcga_combined_score$auc,2)))) +
  labs(
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(legend.position = c(1.19, -0.01), 
        legend.justification = c(1.32, -0.25), 
        legend.title = element_blank(),
        legend.background = element_rect(linetype = "solid", colour = "black"),
        legend.text = element_text(size = 15, face = "bold"),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 15)) + 
        coord_fixed() +
  theme(panel.background = element_rect(fill = "white", color = NA))
  
```
