---
title: "Leiden cluster"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

# Length 18

```{r}
top_bottom_tcr_18 <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/top_bottom_tcr_18_I.csv")
top_bottom_tcr_15 <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/top_bottom_tcr_15_I.csv")
```

```{r}
distance_matrix_18 <- matrix(0, nrow = 200, ncol = 200)
for (i in 1:200) {
  chain1 <- top_bottom_tcr_18$cdr3[i]
  for (j in 1:200) {
    chain2 <- top_bottom_tcr_18$cdr3[j]
    distance_matrix_18[i,j] <- TcrDistCalculator(chain1, chain2)
  }
}

relation_matrix_18 <- matrix(0, nrow = nrow(distance_matrix_18), ncol = ncol(distance_matrix_18))
relation_matrix_18[distance_matrix_18 < 80] <- 1
graph <- graph_from_adjacency_matrix(relation_matrix_18, mode = "undirected")
vertex_labels <- rep("", vcount(graph))
vertex_labels[1:100] <- "top tcr"
vertex_labels[101:200] <- "bottom tcr"

similarity_matrix <- -distance_matrix_18
threshold <- quantile(similarity_matrix, 0.9)  
adjacency_matrix <- ifelse(similarity_matrix > threshold, similarity_matrix, 0)

graph <- graph_from_adjacency_matrix(adjacency_matrix, mode = "undirected", weighted = TRUE)

result <- leiden_find_partition(
  graph,
  partition_type = "ModularityVertexPartition",  
  resolution_parameter = 1.0,  
  num_iter = 2  
)

clusters <- result$membership

tsne_result <- Rtsne(as.dist(distance_matrix_18), is_distance = TRUE)

df_tsne <- as.data.frame(tsne_result$Y)
colnames(df_tsne) <- c("Dim1", "Dim2")  
df_tsne$cluster <- as.factor(clusters)

cluster_sizes <- df_tsne %>% group_by(cluster) %>% summarise(size = n())

df_tsne <- df_tsne %>%
  left_join(cluster_sizes, by = "cluster") %>%
  mutate(shape = ifelse(size <= 5, "small", "large"),
         cluster = ifelse(size <= 5, "small_cluster", cluster))  

df_tsne$group <- ifelse(1:nrow(df_tsne) <= 100, "Top", "Bottom")

df_six_clusters <- df_tsne %>% filter(cluster %in% c("1", "2", "3", "4", "5", "6"))

cluster_group_ratio <- df_six_clusters %>%
  group_by(cluster, group) %>%
  summarise(count = n()) %>%
  group_by(cluster) %>%
  mutate(ratio = count / sum(count)) %>%
  select(cluster, group, ratio)

heatmap_data_18 <- dcast(cluster_group_ratio, cluster ~ group, value.var = "ratio", fill = 0)
```

# Heatmap

```{r}
ggplot(melt(heatmap_data_18, id.vars = "cluster"), aes(x = variable, y = cluster, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "white", high = "blue", 
                      breaks = c(0.25, 0.5, 0.75)) +  
  theme_minimal() +
  labs(title = "CDR3 Length = 18", x = "Group", y = "Cluster", fill = "Proportion") +
  theme(
    plot.title = element_text(size = 20, face = "bold"),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),    
    legend.text = element_text(size = 12, face = "bold"),      
    legend.key.height = unit(1.5, "cm"),                 
    legend.key.width = unit(0.4, "cm"),                      
    legend.title.align = 0.5                                 
  )
```

# Length 15

```{r}
distance_matrix_15 <- matrix(0, nrow = 200, ncol = 200)
for (i in 1:200) {
  chain1 <- top_bottom_tcr_15$cdr3[i]
  for (j in 1:200) {
    chain2 <- top_bottom_tcr_15$cdr3[j]
    distance_matrix_15[i,j] <- TcrDistCalculator(chain1, chain2)
  }
}

similarity_matrix <- -distance_matrix_15
threshold <- quantile(similarity_matrix, 0.9)  
adjacency_matrix <- ifelse(similarity_matrix > threshold, similarity_matrix, 0)

graph <- graph_from_adjacency_matrix(adjacency_matrix, mode = "undirected", weighted = TRUE)

result <- leiden_find_partition(
  graph,
  partition_type = "ModularityVertexPartition",  
  resolution_parameter = 1.0,  
  num_iter = 2  
)

clusters <- result$membership

tsne_result <- Rtsne(as.dist(distance_matrix_18), is_distance = TRUE)

df_tsne <- as.data.frame(tsne_result$Y)
colnames(df_tsne) <- c("Dim1", "Dim2")  
df_tsne$cluster <- as.factor(clusters)

cluster_sizes <- df_tsne %>% group_by(cluster) %>% summarise(size = n())

df_tsne <- df_tsne %>%
  left_join(cluster_sizes, by = "cluster") %>%
  mutate(shape = ifelse(size <= 5, "small", "large"),
         cluster = ifelse(size <= 5, "small_cluster", cluster))  # 将小簇标记为 'small_cluster'

df_tsne$group <- ifelse(1:nrow(df_tsne) <= 100, "Top", "Bottom")

df_six_clusters <- df_tsne %>% filter(cluster %in% c("1", "2", "3", "4", "5", "6"))

cluster_group_ratio <- df_six_clusters %>%
  group_by(cluster, group) %>%
  summarise(count = n()) %>%
  group_by(cluster) %>%
  mutate(ratio = count / sum(count)) %>%
  select(cluster, group, ratio)

heatmap_data_15 <- dcast(cluster_group_ratio, cluster ~ group, value.var = "ratio", fill = 0)
```

# Heatmap

```{r}
ggplot(melt(heatmap_data_15, id.vars = "cluster"), aes(x = variable, y = cluster, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "white", high = "blue", 
                      breaks = c(0.25, 0.5, 0.75)) +  
  theme_minimal() +
  labs(title = "CDR3 Length = 15", x = "Group", y = "Cluster", fill = "Proportion") +
  theme(
    plot.title = element_text(size = 20, face = "bold"),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 14, face = "bold"),
    legend.title = element_text(size = 14, face = "bold"),    
    legend.text = element_text(size = 12, face = "bold"),      
    legend.key.height = unit(1.5, "cm"),                 
    legend.key.width = unit(0.4, "cm"),                      
    legend.title.align = 0.5                                 
  )
```