---
title: "length_distribution"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
emerson_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/emerson_pairs_I.csv")
delmonte_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/delmonte_pairs_I.csv")
```

# for delmonte

```{r}
ggplot(delmonte_pairs_I, aes(x = length, fill = as.factor(class))) +
  geom_histogram(position = "identity", alpha = 0.6, binwidth = 1, boundary = 0.5, aes(y = after_stat(density))) +

  scale_fill_manual(values = c("#FF9999", "#99CCFF"), labels = c("negative", "positive")) +
  
  scale_x_continuous(limits = c(8, 20), breaks = seq(8, 20, by = 1)) +
  
  labs(title = "Length Distribution by Class", x = "CDR3 Length", y = "Density", fill = "Class") +
  
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20, face = "bold"),  
    axis.title.x = element_text(size = 16, face = "bold"),  
    axis.title.y = element_text(size = 16, face = "bold"),  
    axis.text.x = element_text(size = 14, face = "bold"),   
    axis.text.y = element_text(size = 14, face = "bold"),   
    legend.title = element_text(size = 14, face = "bold"),  
    legend.text = element_text(size = 12, face = "bold")    
  )
```

```{r}
ggplot(delmonte_pairs_I, aes(x = length, fill = as.factor(class))) +
  geom_histogram(position = position_dodge(width = 0.9), alpha = 0.6, binwidth = 1, boundary = 0.5, aes(y = after_stat(density))) +

  scale_fill_manual(values = c("#FF9999", "#99CCFF"), labels = c("negative", "positive")) +
  
  scale_x_continuous(limits = c(8, 20), breaks = seq(8, 20, by = 1)) +
  
  labs(title = "Length Distribution by Class", x = "CDR3 Length", y = "Density", fill = "Class") +
  
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20, face = "bold"),  
    axis.title.x = element_text(size = 16, face = "bold"),  
    axis.title.y = element_text(size = 16, face = "bold"),  
    axis.text.x = element_text(size = 14, face = "bold"),   
    axis.text.y = element_text(size = 14, face = "bold"),   
    legend.title = element_text(size = 14, face = "bold"),  
    legend.text = element_text(size = 12, face = "bold")    
  )

```

# for emerson

```{r}
ggplot(emerson_pairs_I, aes(x = length, fill = as.factor(class))) +
  geom_histogram(position = "identity", alpha = 0.6, binwidth = 1, boundary = 0.5, aes(y = after_stat(density))) +

  scale_fill_manual(values = c("#FF9999", "#99CCFF"), labels = c("negative", "positive")) +
  
  scale_x_continuous(limits = c(8, 20), breaks = seq(8, 20, by = 1)) +
  
  labs(title = "Length Distribution by Class", x = "CDR3 Length", y = "Density", fill = "Class") +
  
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20, face = "bold"),  
    axis.title.x = element_text(size = 16, face = "bold"),  
    axis.title.y = element_text(size = 16, face = "bold"),  
    axis.text.x = element_text(size = 14, face = "bold"),   
    axis.text.y = element_text(size = 14, face = "bold"),   
    legend.title = element_text(size = 14, face = "bold"),  
    legend.text = element_text(size = 12, face = "bold")    
  )
```

```{r}
ggplot(emerson_pairs_I, aes(x = length, fill = as.factor(class))) +
  geom_histogram(position = position_dodge(width = 0.9), alpha = 0.6, binwidth = 1, boundary = 0.5, aes(y = after_stat(density))) +

  scale_fill_manual(values = c("#FF9999", "#99CCFF"), labels = c("negative", "positive")) +
  
  scale_x_continuous(limits = c(8, 20), breaks = seq(8, 20, by = 1)) +
  
  labs(title = "Length Distribution by Class", x = "CDR3 Length", y = "Density", fill = "Class") +
  
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20, face = "bold"),  
    axis.title.x = element_text(size = 16, face = "bold"),  
    axis.title.y = element_text(size = 16, face = "bold"),  
    axis.text.x = element_text(size = 14, face = "bold"),   
    axis.text.y = element_text(size = 14, face = "bold"),   
    legend.title = element_text(size = 14, face = "bold"),  
    legend.text = element_text(size = 12, face = "bold")    
  )

```