---
title: "tgp_depth_mean_score_relationship"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
delmonte_top10000_tcr_sample <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/delmonte_top10000_tcr_sample.csv")
```

```{r}
ggplot(data = delmonte_top10000_tcr_sample, mapping = aes(x = mean_score_hla1, y = -log10(tgp))) +
  geom_pointdensity() +
  scale_color_viridis_c() + 
  ylab(expression(-log[10](TGP))) +
  xlab("DePTH mean score") +
  theme(text = element_text(size = 16), 
        axis.title = element_text(size = 18), 
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 16), 
        legend.text = element_text(size = 14)) 
```

```{r}
ggplot(data = delmonte_top10000_tcr_sample, mapping = aes(x = mean_score_hla2, y = -log10(tgp))) +
  geom_pointdensity() +
  scale_color_viridis_c() + 
  ylab(expression(-log[10](TGP))) +
  xlab("DePTH mean score") +
  theme(text = element_text(size = 16), 
        axis.title = element_text(size = 18), 
        axis.text = element_text(size = 16),
        legend.title = element_text(size = 16), 
        legend.text = element_text(size = 14)) 
```
