---
title: "emerson_evaluation"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

## Emerson test

```{r}
emerson_test_II_pos <- read.csv("/Users/fuminli/Desktop/TCR\ project/HLA_II_all_match/test_pos/predicted_scores.csv")
emerson_test_II_neg <- read.csv("/Users/fuminli/Desktop/TCR\ project/HLA_II_all_match/test_neg/predicted_scores.csv")
```

```{r}
emerson_test_II_neg$class = 0
emerson_test_II_pos$class = 1
emerson_test_II <- rbind(emerson_test_II_neg, emerson_test_II_pos)
```

```{r}
emerson_test_II_pos <- read.csv("/Users/fuminli/Desktop/TCR\ project/HLA_II_all_match/test_pos/predicted_scores.csv")
emerson_test_II_neg <- read.csv("/Users/fuminli/Desktop/TCR\ project/HLA_II_all_match/test_neg/predicted_scores.csv")
```

```{r}
emerson_test_II_neg$class = 0
emerson_test_II_pos$class = 1
emerson_test_II <- rbind(emerson_test_II_neg, emerson_test_II_pos)
```

```{r}
emerson_test_II <- separate(emerson_test_II, tcr, into = c("v", "tcr"), sep = ",")
```

```{r}
write.table(emerson_test_II$tcr, "/Users/fuminli/Desktop/TCR project/test_tgp.tsv", sep = "\t", quote = FALSE, row.names = FALSE)
```

```{r}
emerson_test_II_tgp <- read.csv("/Users/fuminli/Desktop/TCR project/test_tgp_result.tsv", header = FALSE, sep = "\t")
colnames(emerson_test_II_tgp) <- c("tcr", "TGP")
emerson_test_II$magnitude <- -log10(emerson_test_II_tgp$TGP)
emerson_test_II$normalized_tgp <- (emerson_test_II$magnitude - 6)/4
emerson_test_II[emerson_test_II$normalized_tgp<0,]$normalized_tgp = 0
emerson_test_II[emerson_test_II$normalized_tgp>1,]$normalized_tgp = 1
```





