---
title: "DePTH_tcga_evaluation"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
sig_pairs$class <- 1
neg_pairs$class <- 0
tcga_test_pairs <- rbind(sig_pairs[,c(1,2,4)], neg_pairs[,c(1,3,7)])
tcga_test_pairs$tcr <- paste0("not_found,", test_pairs$tcr)
colnames(tcga_test_pairs)[2] <- "hla_allele"
```

```{r}
write.csv(tcga_test_pairs[, c(1,2)], "/Users/fuminli/Desktop/TCR project/TCGA_clean/tcga_test_pairs.csv")
```

Use the following code to evaluate DePTH:

DePTH predict --test_file "/Users/fuminli/Desktop/TCR project/TCGA_clean/tcga_test_pairs.csv" \
              --hla_class HLA_I \
              --output_dir "/Users/fuminli/Desktop/TCR project/TCGA_clean/tcga_test_pairs_result"
              
```{r}
tcga_test_pairs_result <- read.csv("/Users/fuminli/Desktop/TCR project/TCGA_clean/tcga_test_pairs_result/predicted_scores.csv")
tcga_test_pairs$score <- tcga_test_pairs_result$score
```

Get AUC and draw ROC curve. We compare the result with Emerson dataset

```{r}
roc_tcga_test <- roc(tcga_test_pairs$class, tcga_test_pairs$score)
roc_tcga_test_df <- data.frame(
  FPR = 1-roc_tcga_test$specificities,
  TPR = roc_tcga_test$sensitivities
)
auc_tcga <- roc_tcga_test$auc
```

```{r}
roc_emerson_test <- roc(emerson_test_pairs$class, emerson_test_pairs$score)
roc_emerson_test_df <- data.frame(
  FPR = 1-roc_emerson_test$specificities,
  TPR = roc_emerson_test$sensitivities
)
auc_emerson <- roc_emerson_test$auc
```

```{r}
roc_emerson_no_v_test <- roc(emerson_test_pairs_no_v$class, emerson_test_pairs_no_v$score)
roc_emerson_no_v_test_df <- data.frame(
  FPR = 1-roc_emerson_no_v_test$specificities,
  TPR = roc_emerson_no_v_test$sensitivities
)
auc_emerson_no_v <- roc_emerson_no_v_test$auc
```

```{r}
ggplot() +
  geom_line(data = roc_tcga_test_df, aes(x = FPR, y = TPR, color = "tcga_auc"), size = 1.5) +
  geom_line(data = roc_emerson_test_df, aes(x = FPR, y = TPR, color = "emerson_auc"), size = 1.5) +
  geom_line(data = roc_emerson_no_v_test_df, aes(x = FPR, y = TPR, color = "emerson_no_v_auc"), size = 1.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", size = 1.5) +
  scale_color_manual(values = c("tcga_auc" = "purple",
                                "emerson_auc" = "blue",
                                "emerson_no_v_auc" = "orange"),
                     labels = c("tcga_auc" = paste("tcga: ", round(auc_tcga, 2)),
                                "emerson_auc" = paste("emerson: ", round(auc_emerson, 2)),
                                "emerson_no_v_auc" = paste("emerson_no_v: ", round(auc_emerson_no_v, 2)))) +
  labs(title = "TCGA evaluation",
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(legend.position = c(1.11, 0.05), 
        legend.justification = c(1.25, 0), 
        legend.title = element_blank(),
        legend.background = element_rect(linetype = "solid", colour = "black"),
        legend.text = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15, face = "bold"),
        axis.title = element_text(size = 15, face = "bold"),
        axis.text = element_text(size = 15, face = "bold"),
        legend.key.size = unit(1.5, 'lines')) + 
  coord_fixed()
```


              