---
title: "tgp_distribution"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
emerson_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/emerson_pairs_I.csv")
delmonte_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/delmonte_pairs_I.csv")
tcga_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/tcga_pairs.csv")
```

```{r}
emerson_pairs_I$source <- 'Emerson'
delmonte_pairs_I$source <- 'Delmonte'
tcga_pairs_I$source <- 'TCGA'

df_combined <- bind_rows(emerson_pairs_I[, c("class", "tgp", "source")], delmonte_pairs_I[, c("class", "tgp", "source")],tcga_pairs_I[, c("class", "tgp", "source")])
```

```{r}
ggplot(df_combined, aes(x = source, y = -log10(tgp), fill = as.factor(class))) +
  geom_violin(trim = FALSE, scale = "width", alpha = 0.6) +

  geom_boxplot(width = 0.1, position = position_dodge(0.9), outlier.shape = 16, outlier.size = 1.5) +

  scale_fill_manual(values = c("firebrick", "steelblue"), labels = c("negative", "positive")) +

  labs(x = "Data source", y = "-log10(TGP)", fill = "Class") +

  theme_minimal() +
  theme(
    axis.text.x = element_text(face = "bold", size = 14), 
    axis.text.y = element_text(size = 12), 
    axis.title.x = element_text(size = 16, face = "bold"), 
    axis.title.y = element_text(size = 16, face = "bold"),  
    legend.text = element_text(size = 12),  
    legend.title = element_text(size = 14, face = "bold"),  
    panel.grid.major = element_line(size = 0.5), 
    panel.grid.minor = element_blank()  
  )
```

