---
title: "select_sig_pairs"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
hla_count <- hla_count[hla_count$count>=5,]
for (table_name in hla_count$hla) {
  table_name <- gsub("\\*", "_", table_name)
  table_name <- gsub(":", "_", table_name)
  file_path <- paste0("/Users/fuminli/Desktop/TCR\ project/ImmuneACCESS_2/",table_name,"_Rout.csv")
  temp <- read.csv(file_path)
  assign(table_name, temp)
  print(table_name)
}
```

```{r}
table_name1 = hla_count$hla[1]
table_name <- gsub("\\*", "_", table_name1)
table_name <- gsub(":", "_", table_name)
temp <- get(table_name)
temp <- temp[temp$fisher_oneside_pval < 0.000001 & temp$fisher_oneside_pval != 0,]
sig_pair <- temp[,c(1,2,3,4)]
sig_pair$hla <- hla_count$hla[1]
sig_pair$hla_count <- hla_count$count[1]

for (i in 2:nrow(hla_count)){
  table_name1 <- hla_count$hla[i]
  table_name <- gsub("\\*", "_", table_name1)
  table_name <- gsub(":", "_", table_name)
  temp <- get(table_name)
  temp <- temp[temp$fisher_oneside_pval < 0.000001 & temp$fisher_oneside_pval != 0,][,c(1,2,3,4)]
  if (length(temp$count)>0) {
    temp$hla <- hla_count$hla[i]
    temp$hla_count <- hla_count$count[i]
    sig_pair <- rbind(sig_pair, temp)
  }
}
rownames(sig_pair)=NULL
```

```{r}
match_indices <- match(sig_pair$tcr, tcr_count$tcr)
sig_pair$v <- ifelse(!is.na(match_indices), tcr_count$v[match_indices], "not_found")
```

```{r}
sig_pair$v <- gsub("0", "", sig_pair$v)
sig_pair$v<- gsub("\\*", "*0", sig_pair$v)
```

```{r}
sig_pair$v <- "not_found"
```


```{r}
sig_pair$v <- gsub("C", "", sig_pair$v)
sig_pair$v <- gsub("TRBV19-1", "TRBV19", sig_pair$v)
sig_pair$v <- gsub("TRBV14-1", "TRBV14", sig_pair$v)
sig_pair$v <- gsub("TRBV27-1", "TRBV27", sig_pair$v)
sig_pair$v <- gsub("TRBV18-1", "TRBV18", sig_pair$v)
sig_pair$v <- gsub("TRBV13-1", "TRBV13", sig_pair$v)
sig_pair$v <- gsub("TRBV28-1", "TRBV28", sig_pair$v)
sig_pair$v <- gsub("TRBV2-1", "TRBV2", sig_pair$v)
sig_pair$v <- gsub("TRBV9-1", "TRBV9", sig_pair$v)
sig_pair$v <- gsub("TRBV16-1", "TRBV16", sig_pair$v)
sig_pair$v <- gsub("TRBV1-1", "TRBV1", sig_pair$v)
sig_pair$v <- gsub("TRBV15-1", "TRBV15", sig_pair$v)
sig_pair$v <- gsub("TRBV1-2\\*01", "not_found", sig_pair$v)
sig_pair$v <- gsub("TRBV1-3\\*01", "not_found", sig_pair$v)
sig_pair$v <- gsub("TRBV6-2\\*02", "not_found", sig_pair$v)
sig_pair$v <- gsub("TRBV3-1\\*05", "not_found", sig_pair$v)
sig_pair$v <- gsub("TRBV2\\*04", "not_found", sig_pair$v)
```

#delete the record whose tcr have *
```{r}
sig_pair <- sig_pair[!grepl("\\*", sig_pair$tcr), , drop = FALSE]
```

```{r}
setdiff(sig_pair$v, combo_xcr$id)
```

```{r}
temp <- sig_pair[,c(1,2,5)]
temp$hla_allele <- paste0("HLA-",sig_pair$hla)
temp$tcr <- paste0(sig_pair$v,",",sig_pair$tcr)
temp <- temp[,c(4,1)]
```

```{r}
write.csv(temp, file = "/Users/fuminli/anaconda3/envs/DePTH_env/immuneaccess_pos.csv", row.names = FALSE)
```

```{r}
sig_pair_score <- read.csv("/Users/fuminli/anaconda3/envs/DePTH_env/immuneaccess_pos/predicted_scores.csv")
sig_pair$score <- sig_pair_score$score
```

```{r}
write.csv(sig_pair_score, "/Users/fuminli/Desktop/TCR\ project/ImmuneACCESS/Delmonte_test_data/sig_pair.csv")
```


