---
title: "tcr_population_frequency_tgp"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
tcr_generation_count <- inner_join(tcr_generation, tcr_count, by = "tcr") %>%
  select(tcr, magnitude, count)
```

```{r}
tcr_generation_count$group <- cut(tcr_generation_count$count,
                  breaks = c(0, 10, 20, 50, 100, Inf),
                  labels = c("5-10", "11-20", "21-50", "51-100", "100+"),
                  right = FALSE)
```

```{r}
ggplot(tcr_generation_count, aes(x = group, y = magnitude)) +
  geom_violin(fill = "cyan", trim = FALSE) + # 设置violin为青色
  geom_boxplot(width = 0.1, fill = "white", color = "black") + # 添加白色填充的box plot，边框为黑色
  labs(x="TCR count", y="Density") +
  theme_minimal() +
  ylab(expression(-log[10](TGP))) +
  theme(text = element_text(size=20, face="bold"),  # Increase size and make text bold
        axis.title.x = element_text(size=15, face="bold"),
        axis.title.y = element_text(size=15, face="bold"),
        axis.text.x = element_text(size=15, face="bold"),
        axis.text.y = element_text(size=15, face="bold"),
        legend.title = element_text(size=15, face="bold"),
        legend.text = element_text(size=15, face="bold")) +
  ylim(c(5, 10))
```

