---
title: "length_analysis"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
delmonte_length_matching_pos_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/model/length_matching_model_I/test/delmonte_test/test_pos_output/avg_predicted_scores.csv")
delmonte_length_matching_neg_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/model/length_matching_model_I/test/delmonte_test/test_neg_output/avg_predicted_scores.csv")
delmonte_pairs_I <- read.csv("/Users/fuminli/Desktop/HLA_TCR_clean/data/delmonte_pairs_I.csv")
```

# DePTH auc across length(length matching model)

```{r}
delmonte_length_matching_pos_I <- separate(delmonte_length_matching_pos_I, tcr, into = c("v", "cdr3"), sep = ",")
delmonte_length_matching_neg_I <- separate(delmonte_length_matching_neg_I, tcr, into = c("v", "cdr3"), sep = ",")
delmonte_length_matching_neg_I$class <- 0
delmonte_length_matching_pos_I$class <- 1
delmonte_length_matching_I <- rbind(delmonte_length_matching_pos_I, delmonte_length_matching_neg_I)
delmonte_length_matching_I$length <- nchar(delmonte_length_matching_I$cdr3)
```

```{r}
delmonte_length_matching_I_11 <- delmonte_length_matching_I[delmonte_length_matching_I$length == 11,]
delmonte_length_matching_I_12 <- delmonte_length_matching_I[delmonte_length_matching_I$length == 12,]
delmonte_length_matching_I_13 <- delmonte_length_matching_I[delmonte_length_matching_I$length == 13,]
delmonte_length_matching_I_14 <- delmonte_length_matching_I[delmonte_length_matching_I$length == 14,]
delmonte_length_matching_I_15 <- delmonte_length_matching_I[delmonte_length_matching_I$length == 15,]
delmonte_length_matching_I_16 <- delmonte_length_matching_I[delmonte_length_matching_I$length == 16,]
```

```{r}
roc_delmonte_length_matching_I_11 <- roc(delmonte_length_matching_I_11$class, delmonte_length_matching_I_11$score)

roc_delmonte_length_matching_I_11_df <- data.frame(
  FPR = 1-roc_delmonte_length_matching_I_11$specificities,
  TPR = roc_delmonte_length_matching_I_11$sensitivities
)

roc_delmonte_length_matching_I_12 <- roc(delmonte_length_matching_I_12$class, delmonte_length_matching_I_12$score)

roc_delmonte_length_matching_I_12_df <- data.frame(
  FPR = 1-roc_delmonte_length_matching_I_12$specificities,
  TPR = roc_delmonte_length_matching_I_12$sensitivities
)

 
roc_delmonte_length_matching_I_13 <- roc(delmonte_length_matching_I_13$class, delmonte_length_matching_I_13$score)

roc_delmonte_length_matching_I_13_df <- data.frame(
  FPR = 1-roc_delmonte_length_matching_I_13$specificities,
  TPR = roc_delmonte_length_matching_I_13$sensitivities
)

roc_delmonte_length_matching_I_14 <- roc(delmonte_length_matching_I_14$class, delmonte_length_matching_I_14$score)

roc_delmonte_length_matching_I_14_df <- data.frame(
  FPR = 1-roc_delmonte_length_matching_I_14$specificities,
  TPR = roc_delmonte_length_matching_I_14$sensitivities
)


roc_delmonte_length_matching_I_15 <- roc(delmonte_length_matching_I_15$class, delmonte_length_matching_I_15$score)

roc_delmonte_length_matching_I_15_df <- data.frame(
  FPR = 1-roc_delmonte_length_matching_I_15$specificities,
  TPR = roc_delmonte_length_matching_I_15$sensitivities
)

roc_delmonte_length_matching_I_16 <- roc(delmonte_length_matching_I_16$class, delmonte_length_matching_I_16$score)

roc_delmonte_length_matching_I_16_df <- data.frame(
  FPR = 1-roc_delmonte_length_matching_I_16$specificities,
  TPR = roc_delmonte_length_matching_I_16$sensitivities
)

auc_delmonte_length_matching_11 <- roc_delmonte_length_matching_I_11$auc
auc_delmonte_length_matching_12 <- roc_delmonte_length_matching_I_12$auc
auc_delmonte_length_matching_13 <- roc_delmonte_length_matching_I_13$auc
auc_delmonte_length_matching_14 <- roc_delmonte_length_matching_I_14$auc
auc_delmonte_length_matching_15 <- roc_delmonte_length_matching_I_15$auc
auc_delmonte_length_matching_16 <- roc_delmonte_length_matching_I_16$auc
```

```{r}
ggplot() +
  geom_line(data = roc_delmonte_length_matching_I_11_df[246:1,], aes(x = FPR, y = TPR, color = "length_11_auc")) +
  geom_line(data = roc_delmonte_length_matching_I_12_df[583:1,], aes(x = FPR, y = TPR, color = "length_12_auc")) +
  geom_line(data = roc_delmonte_length_matching_I_13_df[1265:1,], aes(x = FPR, y = TPR, color = "length_13_auc")) +
  geom_line(data = roc_delmonte_length_matching_I_14_df[1555:1,], aes(x = FPR, y = TPR, color = "length_14_auc")) +
  geom_line(data = roc_delmonte_length_matching_I_15_df[1202:1,], aes(x = FPR, y = TPR, color = "length_15_auc")) +
  geom_line(data = roc_delmonte_length_matching_I_16_df[346:1,], aes(x = FPR, y = TPR, color = "length_16_auc")) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("length_11_auc" = "blue",
                                 "length_12_auc" = "red",
                                 "length_13_auc" = "green",
                                 "length_14_auc" = "orange",
                                 "length_15_auc" = "purple",
                                 "length_16_auc" = "black"),
                      labels = c("length_11_auc" = paste("11: ", round(auc_delmonte_length_matching_11,2)),
                                 "length_12_auc" = paste("12: ", round(auc_delmonte_length_matching_12,2)),
                                "length_13_auc" = paste("13: ", round(auc_delmonte_length_matching_13,2)),
                                "length_14_auc" = paste("14: ", round(auc_delmonte_length_matching_14,2)),
                                "length_15_auc" = paste("15: ", round(auc_delmonte_length_matching_15,2)),
                                "length_16_auc" = paste("16: ", round(auc_delmonte_length_matching_16,2)))) +
  labs(title = "Length matching model+Delmonte",
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(
  legend.position = c(1.11, 0.05),
  legend.justification = c(1.25, 0),
  legend.title = element_blank(),
  legend.background = element_rect(linetype = "solid", colour = "black"),
  legend.text = element_text(size = 15, face = "bold"),
  plot.title = element_text(size = 15, face = "bold"),
  axis.text = element_text(size = 14, face = "bold"),  
  axis.title = element_text(size = 16, face = "bold")  
) + 
coord_fixed()
```

# DePTH auc across length(original model)

```{r}
delmonte_pairs_I_11 <- delmonte_pairs_I[delmonte_pairs_I$length == 11,]
delmonte_pairs_I_12 <- delmonte_pairs_I[delmonte_pairs_I$length == 12,]
delmonte_pairs_I_13 <- delmonte_pairs_I[delmonte_pairs_I$length == 13,]
delmonte_pairs_I_14 <- delmonte_pairs_I[delmonte_pairs_I$length == 14,]
delmonte_pairs_I_15 <- delmonte_pairs_I[delmonte_pairs_I$length == 15,]
delmonte_pairs_I_16 <- delmonte_pairs_I[delmonte_pairs_I$length == 16,]
```

```{r}
roc_delmonte_I_11 <- roc(delmonte_pairs_I_11$class, delmonte_pairs_I_11$score)
roc_delmonte_I_11_df <- data.frame(
  FPR = 1-roc_delmonte_I_11$specificities,
  TPR = roc_delmonte_I_11$sensitivities
)

roc_delmonte_I_12 <- roc(delmonte_pairs_I_12$class, delmonte_pairs_I_12$score)
roc_delmonte_I_12_df <- data.frame(
  FPR = 1-roc_delmonte_I_12$specificities,
  TPR = roc_delmonte_I_12$sensitivities
)

roc_delmonte_I_13 <- roc(delmonte_pairs_I_13$class, delmonte_pairs_I_13$score)
roc_delmonte_I_13_df <- data.frame(
  FPR = 1-roc_delmonte_I_13$specificities,
  TPR = roc_delmonte_I_13$sensitivities
)

roc_delmonte_I_14 <- roc(delmonte_pairs_I_14$class, delmonte_pairs_I_14$score)
roc_delmonte_I_14_df <- data.frame(
  FPR = 1-roc_delmonte_I_14$specificities,
  TPR = roc_delmonte_I_14$sensitivities
)

roc_delmonte_I_15 <- roc(delmonte_pairs_I_15$class, delmonte_pairs_I_15$score)
roc_delmonte_I_15_df <- data.frame(
  FPR = 1-roc_delmonte_I_15$specificities,
  TPR = roc_delmonte_I_15$sensitivities
)

roc_delmonte_I_16 <- roc(delmonte_pairs_I_16$class, delmonte_pairs_I_16$score)
roc_delmonte_I_16_df <- data.frame(
  FPR = 1-roc_delmonte_I_16$specificities,
  TPR = roc_delmonte_I_16$sensitivities
)

auc_delmonte_11 <- roc_delmonte_I_11$auc
auc_delmonte_12 <- roc_delmonte_I_12$auc
auc_delmonte_13 <- roc_delmonte_I_13$auc
auc_delmonte_14 <- roc_delmonte_I_14$auc
auc_delmonte_15 <- roc_delmonte_I_15$auc
auc_delmonte_16 <- roc_delmonte_I_16$auc
```

```{r}
ggplot() +
  geom_line(data = roc_delmonte_I_11_df[246:1,], aes(x = FPR, y = TPR, color = "length_11_auc")) +
  geom_line(data = roc_delmonte_I_12_df[583:1,], aes(x = FPR, y = TPR, color = "length_12_auc")) +
  geom_line(data = roc_delmonte_I_13_df[1265:1,], aes(x = FPR, y = TPR, color = "length_13_auc")) +
  geom_line(data = roc_delmonte_I_14_df[1555:1,], aes(x = FPR, y = TPR, color = "length_14_auc")) +
  geom_line(data = roc_delmonte_I_15_df[1202:1,], aes(x = FPR, y = TPR, color = "length_15_auc")) +
  geom_line(data = roc_delmonte_I_16_df[346:1,], aes(x = FPR, y = TPR, color = "length_16_auc")) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("length_11_auc" = "blue",
                                 "length_12_auc" = "red",
                                 "length_13_auc" = "green",
                                 "length_14_auc" = "orange",
                                 "length_15_auc" = "purple",
                                 "length_16_auc" = "black"),
                     labels = c("length_11_auc" = paste("11: ", round(auc_delmonte_11,2)),
                                "length_12_auc" = paste("12: ", round(auc_delmonte_12,2)),
                                "length_13_auc" = paste("13: ", round(auc_delmonte_13,2)),
                                "length_14_auc" = paste("14: ", round(auc_delmonte_14,2)),
                                "length_15_auc" = paste("15: ", round(auc_delmonte_15,2)),
                                "length_16_auc" = paste("16: ", round(auc_delmonte_16,2)))) +
  labs(title = "Original model+Delmonte",
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(
  legend.position = c(1.11, 0.05),
  legend.justification = c(1.25, 0),
  legend.title = element_blank(),
  legend.background = element_rect(linetype = "solid", colour = "black"),
  legend.text = element_text(size = 15, face = "bold"),
  plot.title = element_text(size = 15, face = "bold"),
  axis.text = element_text(size = 14, face = "bold"),  
  axis.title = element_text(size = 16, face = "bold")  
) + 
coord_fixed()
```



