---
title: "length_analysis"
author: "Fumin Li"
date: "`r Sys.Date()`"
output: html_document
---


# length analysis for emerson
```{r}
emerson_test_II_2 <- separate(emerson_test_II_2, tcr, into = c("v", "tcr"), sep = ",")
emerson_test_II_2$length <- nchar(emerson_test_II_2$tcr)
```

```{r}
emerson_test_II_11 <- emerson_test_II_2[emerson_test_II_2$length == 11,]
emerson_test_II_12 <- emerson_test_II_2[emerson_test_II_2$length == 12,]
emerson_test_II_13 <- emerson_test_II_2[emerson_test_II_2$length == 13,]
emerson_test_II_14 <- emerson_test_II_2[emerson_test_II_2$length == 14,]
emerson_test_II_15 <- emerson_test_II_2[emerson_test_II_2$length == 15,]
emerson_test_II_16 <- emerson_test_II_2[emerson_test_II_2$length == 16,]
```

```{r}
roc_emerson_test11 <- roc(emerson_test_II_11$class, emerson_test_II_11$score)
roc_emerson_test11_df <- data.frame(
  FPR = 1-roc_emerson_test11$specificities,
  TPR = roc_emerson_test11$sensitivities
)

roc_emerson_test12 <- roc(emerson_test_II_12$class, emerson_test_II_12$score)
roc_emerson_test12_df <- data.frame(
  FPR = 1-roc_emerson_test12$specificities,
  TPR = roc_emerson_test12$sensitivities
)

roc_emerson_test13 <- roc(emerson_test_II_13$class, emerson_test_II_13$score)
roc_emerson_test13_df <- data.frame(
  FPR = 1-roc_emerson_test13$specificities,
  TPR = roc_emerson_test13$sensitivities
)

roc_emerson_test14 <- roc(emerson_test_II_14$class, emerson_test_II_14$score)
roc_emerson_test14_df <- data.frame(
  FPR = 1-roc_emerson_test14$specificities,
  TPR = roc_emerson_test14$sensitivities
)

roc_emerson_test15 <- roc(emerson_test_II_15$class, emerson_test_II_15$score)
roc_emerson_test15_df <- data.frame(
  FPR = 1-roc_emerson_test15$specificities,
  TPR = roc_emerson_test15$sensitivities
)

roc_emerson_test16 <- roc(emerson_test_II_16$class, emerson_test_II_16$score)
roc_emerson_test16_df <- data.frame(
  FPR = 1-roc_emerson_test16$specificities,
  TPR = roc_emerson_test16$sensitivities
)

auc_11 <- roc_emerson_test11$auc
auc_12 <- roc_emerson_test12$auc
auc_13 <- roc_emerson_test13$auc
auc_14 <- roc_emerson_test14$auc
auc_15 <- roc_emerson_test15$auc
auc_16 <- roc_emerson_test16$auc
```

```{r}
ggplot() +
  geom_line(data = roc_emerson_test11_df, aes(x = FPR, y = TPR, color = "length_11_auc")) +
  geom_line(data = roc_emerson_test12_df, aes(x = FPR, y = TPR, color = "length_12_auc")) +
  geom_line(data = roc_emerson_test13_df, aes(x = FPR, y = TPR, color = "length_13_auc")) +
  geom_line(data = roc_emerson_test14_df, aes(x = FPR, y = TPR, color = "length_14_auc")) +
  geom_line(data = roc_emerson_test15_df, aes(x = FPR, y = TPR, color = "length_15_auc")) +
  geom_line(data = roc_emerson_test16_df[577:1,], aes(x = FPR, y = TPR, color = "length_16_auc")) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("length_11_auc" = "blue",
                                 "length_12_auc" = "red",
                                 "length_13_auc" = "green",
                                 "length_14_auc" = "orange",
                                 "length_15_auc" = "purple",
                                 "length_16_auc" = "black"),
                     labels = c("length_11_auc" = paste("11: ", round(auc_11,2)),
                                "length_12_auc" = paste("12: ", round(auc_12,2)),
                                "length_13_auc" = paste("13: ", round(auc_13,2)),
                                "length_14_auc" = paste("14: ", round(auc_14,2)),
                                "length_15_auc" = paste("15: ", round(auc_15,2)),
                                "length_16_auc" = paste("16: ", round(auc_16,2)))) +
  labs(title = "Original model+Emerson",
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(legend.position = c(1.11, 0.05), 
        legend.justification = c(1.25, 0), 
        legend.title = element_blank(),
        legend.background = element_rect(linetype = "solid", colour = "black"),
        legend.text = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15, face = "bold")) + 
        coord_fixed()
```

```{r}
test_pair_II$length <- nchar(test_pair_II$tcr)
```

```{r}
test_pair_II_11 <- test_pair_II[test_pair_II$length == 11,]
test_pair_II_12 <- test_pair_II[test_pair_II$length == 12,]
test_pair_II_13 <- test_pair_II[test_pair_II$length == 13,]
test_pair_II_14 <- test_pair_II[test_pair_II$length == 14,]
test_pair_II_15 <- test_pair_II[test_pair_II$length == 15,]
test_pair_II_16 <- test_pair_II[test_pair_II$length == 16,]
```

```{r}
roc_delmonte_test11 <- roc(test_pair_II_11$class, test_pair_II_11$score)
roc_delmonte_test11_df <- data.frame(
  FPR = 1-roc_delmonte_test11$specificities,
  TPR = roc_delmonte_test11$sensitivities
)

roc_delmonte_test12 <- roc(test_pair_II_12$class, test_pair_II_12$score)
roc_delmonte_test12_df <- data.frame(
  FPR = 1-roc_delmonte_test12$specificities,
  TPR = roc_delmonte_test12$sensitivities
)

roc_delmonte_test13 <- roc(test_pair_II_13$class, test_pair_II_13$score)
roc_delmonte_test13_df <- data.frame(
  FPR = 1-roc_delmonte_test13$specificities,
  TPR = roc_delmonte_test13$sensitivities
)

roc_delmonte_test14 <- roc(test_pair_II_14$class, test_pair_II_14$score)
roc_delmonte_test14_df <- data.frame(
  FPR = 1-roc_delmonte_test14$specificities,
  TPR = roc_delmonte_test14$sensitivities
)

roc_delmonte_test15 <- roc(test_pair_II_15$class, test_pair_II_15$score)
roc_delmonte_test15_df <- data.frame(
  FPR = 1-roc_delmonte_test15$specificities,
  TPR = roc_delmonte_test15$sensitivities
)

roc_delmonte_test16 <- roc(test_pair_II_16$class, test_pair_II_16$score)
roc_delmonte_test16_df <- data.frame(
  FPR = 1-roc_delmonte_test16$specificities,
  TPR = roc_delmonte_test16$sensitivities
)

auc_11_delmonte <- roc_delmonte_test11$auc
auc_12_delmonte <- roc_delmonte_test12$auc
auc_13_delmonte <- roc_delmonte_test13$auc
auc_14_delmonte <- roc_delmonte_test14$auc
auc_15_delmonte <- roc_delmonte_test15$auc
auc_16_delmonte <- roc_delmonte_test16$auc
```

```{r}
ggplot() +
  geom_line(data = roc_delmonte_test11_df, aes(x = FPR, y = TPR, color = "length_11_auc")) +
  geom_line(data = roc_delmonte_test12_df, aes(x = FPR, y = TPR, color = "length_12_auc")) +
  geom_line(data = roc_delmonte_test13_df, aes(x = FPR, y = TPR, color = "length_13_auc")) +
  geom_line(data = roc_delmonte_test14_df, aes(x = FPR, y = TPR, color = "length_14_auc")) +
  geom_line(data = roc_delmonte_test15_df, aes(x = FPR, y = TPR, color = "length_15_auc")) +
  geom_line(data = roc_delmonte_test16_df[1897:1,], aes(x = FPR, y = TPR, color = "length_16_auc")) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  scale_color_manual(values = c("length_11_auc" = "blue",
                                 "length_12_auc" = "red",
                                 "length_13_auc" = "green",
                                 "length_14_auc" = "orange",
                                 "length_15_auc" = "purple",
                                 "length_16_auc" = "black"),
                     labels = c("length_11_auc" = paste("11: ", round(auc_11_delmonte,2)),
                                "length_12_auc" = paste("12: ", round(auc_12_delmonte,2)),
                                "length_13_auc" = paste("13: ", round(auc_13_delmonte,2)),
                                "length_14_auc" = paste("14: ", round(auc_14_delmonte,2)),
                                "length_15_auc" = paste("15: ", round(auc_15_delmonte,2)),
                                "length_16_auc" = paste("16: ", round(auc_16_delmonte,2)))) +
  labs(title = "Original model+Delmonte",
       x = "FPR",
       y = "TPR") +
  theme_minimal() +
  theme(legend.position = c(1.11, 0.05), 
        legend.justification = c(1.25, 0), 
        legend.title = element_blank(),
        legend.background = element_rect(linetype = "solid", colour = "black"),
        legend.text = element_text(size = 15, face = "bold"),
        plot.title = element_text(size = 15, face = "bold")) + 
        coord_fixed()
```

```{r}
hla_II_top_tcr_test$length <- nchar(hla_II_top_tcr_test$tcr)
```

```{r}
ggplot(hla_II_top_tcr_test[hla_II_top_tcr_test$length > 10 & hla_II_top_tcr_test$length < 19,], aes(x = factor(length), y = mean_score)) +
  geom_violin(fill = "#00FFFF") +  
  geom_boxplot(width = 0.1, color = "black") +  
  labs(x = "Length", y = "Mean Score") +  
  theme_minimal() + 
  theme(legend.position = "none") 
```

